### ISSUE TITLE
IE 8

### ISSUE THREAD

**Issue by luisdalmolin** [globocom/sawpf#13]
No IE8 não aparece mensagem de atualização.

Não acham que já seria hora de adicionar?

**Comment by jefms** [comment]
Eu apoio, já está na hora.
Facilitaria bastante.

att,

Jeferson Sigales
_www.jefms.com_
_facebook.com/jefms_
_twitter.com/jefms_
*
*
*
*

2012/11/27 Luís Dalmolin notifications@github.com

**Comment by davidsonfellipe** [comment]
@luisdalmolin Acho um bom momento sim.

**Comment by fsouza** [comment]
O downside é que a Microsoft pretende suportar o Windows XP até o ano que vem... mas pode ser uma boa forma de fazer as pessoas pararem de usar o Internet Explorer :-)

**Comment by luisdalmolin** [comment]
Talvez uma opção seria manter a versão atual e criar uma versão alternativa disparando a janela de atualização no IE8.

**Comment by kazzkiq** [comment]
O problema é que quem usa Windows XP não poderá atualizar o navegador para a versão 9 ou acima. E tanto usuários do XP quanto do Vista não receberão mais atualizações após o IE9.

Mas de qualquer modo seria uma boa alternativa para dar uma mãozinha para os usuários deixarem o IE e partirem para outro browser.
