### ISSUE TITLE
sawpf.com fora do ar!

### ISSUE THREAD

**Issue by ricardobelo** [globocom/sawpf#14]
Está havendo algum problema na publicação deste script, pois o domínio não está acessível, fazendo com que todos os que o utilizam sejam redirecionados para outros sites.

Abraços!

**Comment by diegofrata** [comment]
Domain Name: sawpf.com
      Created on..............: 2010-05-17
      Expires on..............: 2013-05-17

:(

**Comment by liperuf** [comment]
o próprio G1 está apontando para o http://sawpf.com
alguém vai tomar fumo.

**Comment by marcospereira** [comment]
Senhores, 

Já resolvemos. Falta apenas propagar o dominio novamente. Obrigado pelo aviso.
