### ISSUE TITLE
ie11 é detectado como Firefox 0

### ISSUE THREAD

**Issue by tonylampada** [globocom/sawpf#18]
Galera,
No IE11, aparece a barra dizendo "seu firefox está desatualizado".

Dando uma debugadinha, parece que o IE tá "se achando"...
Tanto que ele nem acha mais que é IE, veja o UserAgent :-)

`"Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; rv:11.0) like Gecko"`

Isso deve estar afetando um monte de gente! :P

**Comment by tonylampada** [comment]
ó só o screenshot

https://dl.dropboxusercontent.com/u/2683925/ie11_se_achando.png

**Comment by edhowler** [comment]
Meu site também está sendo afetado! +1

**Comment by willianribeiro** [comment]
Estou tendo esse problema também !

**Comment by deniscostadsc** [comment]
Tem uma galera juntando grana no FreedomSponsors para pagar para quem resolver essa issue.

http://www.freedomsponsors.org/core/issue/350/ie11-e-detectado-como-firefox-0

**Comment by evertonfraga** [comment]
Posso estar errado, mas o Trident não denuncia?

**Comment by timotta** [comment]
Vou tentar corrigir isso ainda essa semana. Aceito sugestões.

**Comment by timotta** [comment]
Caros,

Segue o commit com a alteração: 

https://github.com/globocom/sawpf/commit/3ae0ea24cdf372d09f02ffcab8b7c5bd9e67992b

Utilizei a string "Trident", que pela que observer somente os Internet Explorers possuem. Para obter a versão utilizei o "rv:" conforme o site da Microsoft recomenda, tomando o cuidado para dar prioridade a "firefox" e "ie".

Podem utilizar essa URL para testar: 

https://raw.github.com/globocom/sawpf/master/src/1.0.js

**Comment by deniscostadsc** [comment]
Muito bom Tiago!

**Comment by willianribeiro** [comment]
Valeu Tiago ! :-)

**Comment by rtancman** [comment]
Tiago aqui ta rolando de boa agora vlw! ;)

**Comment by alisonalonso** [comment]
Prezados, alguma previsão para que este fix fique disponível através da URL principal do sawpf?
Se acessarmos o site da http://salveaweb.com/ com o IE 11, o bug pula na cara... rs...

Abraço.

**Comment by timotta** [comment]
Precisamos que mais alguém valide se está correto, poderia nos ajudar @alisonalonso ?

**Comment by alisonalonso** [comment]
Opa... Claro que sim @timotta ....
Teste realizado! Resultado - ok

```
Versão do IE: 11.0.9600.16476
UserAgent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; MDDS; .NET4.0C; Tablet PC 2.0; .NET4.0E; rv:11.0) like Gecko
```

Abraço!

**Comment by timotta** [comment]
Vou agendar para subir e informo vcs.

**Comment by gabpaladino** [comment]
alguma novidade sobre isso? só fomos perceber o problema ao liberar um novo projeto e o cliente reclamar de uma barra estranha aparecendo! =/

**Comment by luisfernandomangia** [comment]
no IE9 e IE10 não esta aparecendo e já são navegadores antigos

**Comment by morpheu** [comment]
Pessoal

Subimos hoje a atualização para identificar corretamente IE11.

**Comment by gabpaladino** [comment]
legal @morpheu o nome do arquivo não foi alterado né?

**Comment by luisfernandomangia** [comment]
seria legal mudar  de acordo com a versão, como http://sawpf.com/1.1.js para não confundi os desenvolvedores.

**Comment by gabpaladino** [comment]
para mim não!!!! rs se mudar eu tenho que entrar em alguns 30 sites para usar a nova, por isso perguntei, prefiro que suba e já funcione nos sites que estão com o script...

**Comment by luisfernandomangia** [comment]
entendi, valeu pelo toque, não tinha pensado nisso.
Aproveitando, alguém já viu que nos IE's 9 e 10 não aparece o aviso de antigo e precisa atualizar. Tem varias funções que rodam no 11 que não roda no  10 e no 9.
