### ISSUE TITLE
Script p/ https (SSL)

### ISSUE THREAD

**Issue by ghost** [globocom/sawpf#9]
Existe a previsão para disponibilização de uma versão com suporte a SSL? Eu utilizo o script em uma loja virtual, mas quando redireciona para o acesso seguro da mesma perde a validação do CSS pois o conteúdo carregado (script, imagens, etc) não estão em SSL também.

Um abraço, parabéns pela iniciativa.

**Comment by ghost** [comment]
...

**Comment by fabiomcosta** [comment]
Oi mmswebinternet,

Não tenho como responder isso, mas seu pedido será levado em conta e em breve teremos uma resposta.

Obrigado.

**Comment by ghost** [comment]
Olá Fabio, obrigado pela resposta!

Um abraço

**Comment by tapajos** [comment]
Tenho o mesmo problema e por isso vou precisar hospedar tudo no meu servidor.

**Comment by ghost** [comment]
Também estava precisando do SSL !

**Comment by evertonfraga** [comment]
+1. outro dia tive que copiar para o server local pelo mesmo motivo
